/*
 Copyright (c) 2014 NetIQ Corporation.  All Rights Reserved.

 THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND TREATIES.  IT MAY NOT BE USED, COPIED,
 DISTRIBUTED, DISCLOSED, ADAPTED, PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT NETIQ'S
 PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT THE
 PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.

 NETIQ PROVIDES THE WORK "AS IS," WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING WITHOUT THE
 IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. NETIQ,
 THE AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT LIABLE FOR ANY CLAIM,
 DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF,
 OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
*/

/**
 *
 * @author  kwester
 */
public class AlarmForm extends javax.swing.JFrame {
    
    /** Creates new form AlarmForm */
    public AlarmForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        alarmPanel = new javax.swing.JPanel();
        alarmElementIcon = new javax.swing.JLabel();
        alarmElementLabel = new javax.swing.JLabel();
        alarmSeverityIcon = new javax.swing.JLabel();
        alarmDescriptionLabel = new javax.swing.JLabel();
        alarmField1NameLabel = new javax.swing.JLabel();
        alarmField1ValueLabel = new javax.swing.JLabel();
        alarmField2NameLabel = new javax.swing.JLabel();
        alarmField2ValueLabel = new javax.swing.JLabel();

        alarmPanel.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        alarmPanel.add(alarmElementIcon, gridBagConstraints);

        alarmElementLabel.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        alarmElementLabel.setText("Some Element");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.NONE;
        gridBagConstraints.ipadx = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        alarmPanel.add(alarmElementLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        alarmPanel.add(alarmSeverityIcon, gridBagConstraints);

        alarmDescriptionLabel.setText("<html><head><body><font=\"Sans Serif\" size=2>Here is a long description of some alarm text that, hey, you might be interested in.  Howdy Howdy Howdy.");
        alarmDescriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 4, 4);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        alarmPanel.add(alarmDescriptionLabel, gridBagConstraints);

        alarmField1NameLabel.setText("Field 1:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        alarmPanel.add(alarmField1NameLabel, gridBagConstraints);

        alarmField1ValueLabel.setText("Value 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        alarmPanel.add(alarmField1ValueLabel, gridBagConstraints);

        alarmField2NameLabel.setText("Some Field 2:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        alarmPanel.add(alarmField2NameLabel, gridBagConstraints);

        alarmField2ValueLabel.setText("Value 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        alarmPanel.add(alarmField2ValueLabel, gridBagConstraints);

        getContentPane().add(alarmPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new AlarmForm().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alarmDescriptionLabel;
    private javax.swing.JLabel alarmElementIcon;
    private javax.swing.JLabel alarmElementLabel;
    private javax.swing.JLabel alarmField1NameLabel;
    private javax.swing.JLabel alarmField1ValueLabel;
    private javax.swing.JLabel alarmField2NameLabel;
    private javax.swing.JLabel alarmField2ValueLabel;
    private javax.swing.JPanel alarmPanel;
    private javax.swing.JLabel alarmSeverityIcon;
    // End of variables declaration//GEN-END:variables
    
}
