/*
 Copyright (c) 2014 NetIQ Corporation.  All Rights Reserved.

 THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND TREATIES.  IT MAY NOT BE USED, COPIED,
 DISTRIBUTED, DISCLOSED, ADAPTED, PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT NETIQ'S
 PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT THE
 PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.

 NETIQ PROVIDES THE WORK "AS IS," WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING WITHOUT THE
 IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. NETIQ,
 THE AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT LIABLE FOR ANY CLAIM,
 DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF,
 OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
*/

/**
 *
 * @author  kwester
 */
public class AlarmNotifyForm extends javax.swing.JFrame {
    
    /** Creates new form AlarmNotifyForm */
    public AlarmNotifyForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        clientPanel = new javax.swing.JPanel();
        eventsLabel = new javax.swing.JLabel();
        eventsScrollPane = new javax.swing.JScrollPane();
        eventsList = new javax.swing.JList();
        openButton = new javax.swing.JButton();
        snoozeLabel = new javax.swing.JLabel();
        snoozeComboBox = new javax.swing.JComboBox();
        snoozeButton = new javax.swing.JButton();
        dismissButtonPanel = new javax.swing.JPanel();
        dismissButton = new javax.swing.JButton();
        dismissAllButton = new javax.swing.JButton();
        selectionLabel = new javax.swing.JLabel();

        clientPanel.setLayout(new java.awt.GridBagLayout());

        eventsLabel.setText("The following alarms have occurred that require attention:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        clientPanel.add(eventsLabel, gridBagConstraints);

        eventsScrollPane.setViewportView(eventsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 8);
        clientPanel.add(eventsScrollPane, gridBagConstraints);

        openButton.setMnemonic('O');
        openButton.setText("Open Element");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        clientPanel.add(openButton, gridBagConstraints);

        snoozeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        snoozeLabel.setText("Click Snooze to resume notifications in:");
        snoozeLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        clientPanel.add(snoozeLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 8, 0);
        gridBagConstraints.weightx = 1.0;
        clientPanel.add(snoozeComboBox, gridBagConstraints);

        snoozeButton.setMnemonic('S');
        snoozeButton.setText("Snooze");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 8, 8);
        clientPanel.add(snoozeButton, gridBagConstraints);

        dismissButtonPanel.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        dismissButton.setMnemonic('D');
        dismissButton.setText("Dismiss");
        dismissButtonPanel.add(dismissButton);

        dismissAllButton.setMnemonic('A');
        dismissAllButton.setText("Dismiss All");
        dismissButtonPanel.add(dismissAllButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        clientPanel.add(dismissButtonPanel, gridBagConstraints);

        selectionLabel.setText("No selection");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 4);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        clientPanel.add(selectionLabel, gridBagConstraints);

        getContentPane().add(clientPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new AlarmNotifyForm().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clientPanel;
    private javax.swing.JButton dismissAllButton;
    private javax.swing.JButton dismissButton;
    private javax.swing.JPanel dismissButtonPanel;
    private javax.swing.JLabel eventsLabel;
    private javax.swing.JList eventsList;
    private javax.swing.JScrollPane eventsScrollPane;
    private javax.swing.JButton openButton;
    private javax.swing.JLabel selectionLabel;
    private javax.swing.JButton snoozeButton;
    private javax.swing.JComboBox snoozeComboBox;
    private javax.swing.JLabel snoozeLabel;
    // End of variables declaration//GEN-END:variables
    
}
